# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_boardroom_max_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('day', 'time', 'user', 'room')]),
        ),
    ]
